import localFont from "next/font/local";
import "./globals.css";

const montserratMedium = localFont({
    src: '../../public/Fonts/Montserrat-Medium.ttf',
    variable: '--font-montserrat-medium',
});

const futuraLight = localFont({
    src: '../../public/Fonts/FuturaCyrillicLight.ttf',
    variable: '--font-futura-light',
});

const futuraMedium = localFont({
    src: '../../public/Fonts/FuturaCyrillicMedium.ttf',
    variable: '--font-futura-medium',
});

const futuraDemi = localFont({
    src: '../../public/Fonts/FuturaCyrillicDemi.ttf',
    variable: '--font-futura-demi',
});

const futuraHeavy = localFont({
    src: '../../public/Fonts/FuturaCyrillicHeavy.ttf',
    variable: '--font-futura-heavy',
});

export const metadata = {
  title: "TheFaceCraft",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserratMedium.variable} ${futuraLight.variable} ${futuraMedium.variable} ${futuraDemi.variable} ${futuraHeavy.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
